services:
    client:
        build: ./client
        ports:
            - 3000:3000
        depends_on:
            - users 
            - manage 
            
    users: 
        build: ./server/users
        ports: 
            - 8000:8000
        env_file: 
            - ./server/users/.env

    manage:
        build: ./server/manage 
        ports: 
            - 8001:8001 
        env_file:
            - ./server/manage/.env